// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-PGL5j9o5MgE82xlIgcJ7x18TBiRAM0',
    appId: '1:763750370551:web:f9f4a90820929c7ffd17f2',
    messagingSenderId: '763750370551',
    projectId: 'khk-cricket-academy',
    authDomain: 'khk-cricket-academy.firebaseapp.com',
    storageBucket: 'khk-cricket-academy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHAQ6CxGCGKKn9GxQB5YEN-_aIN-45KhQ',
    appId: '1:763750370551:android:74962e1518f00e9dfd17f2',
    messagingSenderId: '763750370551',
    projectId: 'khk-cricket-academy',
    storageBucket: 'khk-cricket-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDNzIDufVStcgsxnJ91QmoqMLyizayAwk',
    appId: '1:763750370551:ios:0f7a3276fff630e3fd17f2',
    messagingSenderId: '763750370551',
    projectId: 'khk-cricket-academy',
    storageBucket: 'khk-cricket-academy.firebasestorage.app',
    iosBundleId: 'com.khkcricket.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDNzIDufVStcgsxnJ91QmoqMLyizayAwk',
    appId: '1:763750370551:ios:21b5c571404c358ffd17f2',
    messagingSenderId: '763750370551',
    projectId: 'khk-cricket-academy',
    storageBucket: 'khk-cricket-academy.firebasestorage.app',
    iosBundleId: 'com.example.khkMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW-PGL5j9o5MgE82xlIgcJ7x18TBiRAM0',
    appId: '1:763750370551:web:8c048a29dfd07e71fd17f2',
    messagingSenderId: '763750370551',
    projectId: 'khk-cricket-academy',
    authDomain: 'khk-cricket-academy.firebaseapp.com',
    storageBucket: 'khk-cricket-academy.firebasestorage.app',
  );
}
